services:
  app:
    build:
      tags: [booru-app:latest]
      network: host
      context: .
    volumes:
      - .env:/app/.env
      - ./.cache:/app/.cache
    ports:
      - 3001:3001
    expose:
      - 3001
