BEGIN;

ALTER TABLE posts_images
  DROP CONSTRAINT posts_images_pkey;

ALTER TABLE posts_images
  RENAME COLUMN id TO hash;

ALTER TABLE posts_images
  ADD COLUMN id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

COMMIT;
