// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3001/' | 'https://localhost:3001/' | (string & {});
};

export type InternalApiActionResponse = {
    message?: string;
    status?: string;
};

export type InternalApiAutocompleteItem = {
    category?: number;
    label?: string;
    post_count?: number;
    value?: string;
};

export type InternalApiErrorResponse = {
    error?: string;
};

export type InternalApiPaginationMeta = {
    count?: number;
    limit?: number;
    next?: string;
    offset?: number;
    previous?: string;
};

export type InternalApiPostItem = {
    created_at?: string;
    file_ext?: string;
    file_size?: number;
    file_url?: string;
    has_children?: boolean;
    has_notes?: boolean;
    hash?: string;
    height?: number;
    id?: number;
    lqip?: string;
    parent_id?: number;
    pixiv_id?: number;
    preview_height?: number;
    preview_url?: string;
    preview_width?: number;
    rating?: 'g' | 's' | 'q' | 'e';
    sample_height?: number;
    sample_url?: string;
    sample_width?: number;
    score?: number;
    source?: string;
    tags?: Array<InternalApiTagItem>;
    width?: number;
};

export type InternalApiPostsListResponse = {
    meta?: InternalApiPaginationMeta;
    post?: Array<InternalApiPostItem>;
};

export type InternalApiTagItem = {
    /**
     * 0: general, 1: artist, 3: copyright, 4: character, 5: meta
     */
    category?: number;
    id?: number;
    name?: string;
};

export type InternalApiWorkerStatusResponse = {
    isRunning?: boolean;
    lastRun?: string;
};

export type GetApiAutocompleteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Tag search query prefix
         */
        q: string;
        /**
         * Maximum suggestions to return (default 10, max 50)
         */
        limit?: number;
    };
    url: '/api/autocomplete';
};

export type GetApiAutocompleteErrors = {
    /**
     * Bad Request
     */
    400: InternalApiErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalApiErrorResponse;
};

export type GetApiAutocompleteError = GetApiAutocompleteErrors[keyof GetApiAutocompleteErrors];

export type GetApiAutocompleteResponses = {
    /**
     * OK
     */
    200: Array<InternalApiAutocompleteItem>;
};

export type GetApiAutocompleteResponse = GetApiAutocompleteResponses[keyof GetApiAutocompleteResponses];

export type GetApiImagesCleanupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/images/cleanup';
};

export type GetApiImagesCleanupErrors = {
    /**
     * Unauthorized
     */
    401: InternalApiErrorResponse;
};

export type GetApiImagesCleanupError = GetApiImagesCleanupErrors[keyof GetApiImagesCleanupErrors];

export type GetApiImagesCleanupResponses = {
    /**
     * OK
     */
    200: InternalApiActionResponse;
};

export type GetApiImagesCleanupResponse = GetApiImagesCleanupResponses[keyof GetApiImagesCleanupResponses];

export type GetApiImagesStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/images/status';
};

export type GetApiImagesStatusErrors = {
    /**
     * Unauthorized
     */
    401: InternalApiErrorResponse;
};

export type GetApiImagesStatusError = GetApiImagesStatusErrors[keyof GetApiImagesStatusErrors];

export type GetApiImagesStatusResponses = {
    /**
     * OK
     */
    200: InternalApiWorkerStatusResponse;
};

export type GetApiImagesStatusResponse = GetApiImagesStatusResponses[keyof GetApiImagesStatusResponses];

export type GetApiImagesTriggerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/images/trigger';
};

export type GetApiImagesTriggerErrors = {
    /**
     * Unauthorized
     */
    401: InternalApiErrorResponse;
    /**
     * Conflict
     */
    409: InternalApiErrorResponse;
};

export type GetApiImagesTriggerError = GetApiImagesTriggerErrors[keyof GetApiImagesTriggerErrors];

export type GetApiImagesTriggerResponses = {
    /**
     * OK
     */
    200: InternalApiActionResponse;
};

export type GetApiImagesTriggerResponse = GetApiImagesTriggerResponses[keyof GetApiImagesTriggerResponses];

export type GetApiPostsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Danbooru search tags query
         */
        tags?: string;
        /**
         * Page number or cursor (e.g. 1, a12345, b12345)
         */
        page?: string;
        /**
         * Number of posts to return (default 50, max 200)
         */
        limit?: number;
    };
    url: '/api/posts';
};

export type GetApiPostsErrors = {
    /**
     * Bad Request
     */
    400: InternalApiErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalApiErrorResponse;
};

export type GetApiPostsError = GetApiPostsErrors[keyof GetApiPostsErrors];

export type GetApiPostsResponses = {
    /**
     * OK
     */
    200: InternalApiPostsListResponse;
};

export type GetApiPostsResponse = GetApiPostsResponses[keyof GetApiPostsResponses];

export type GetApiPostsByIdData = {
    body?: never;
    path: {
        /**
         * Post ID
         */
        id: number;
    };
    query?: never;
    url: '/api/posts/{id}';
};

export type GetApiPostsByIdErrors = {
    /**
     * Not Found
     */
    404: InternalApiErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalApiErrorResponse;
};

export type GetApiPostsByIdError = GetApiPostsByIdErrors[keyof GetApiPostsByIdErrors];

export type GetApiPostsByIdResponses = {
    /**
     * OK
     */
    200: InternalApiPostItem;
};

export type GetApiPostsByIdResponse = GetApiPostsByIdResponses[keyof GetApiPostsByIdResponses];

export type GetApiPostsByIdTagsData = {
    body?: never;
    path: {
        /**
         * Post ID
         */
        id: number;
    };
    query?: never;
    url: '/api/posts/{id}/tags';
};

export type GetApiPostsByIdTagsErrors = {
    /**
     * Not Found
     */
    404: InternalApiErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalApiErrorResponse;
};

export type GetApiPostsByIdTagsError = GetApiPostsByIdTagsErrors[keyof GetApiPostsByIdTagsErrors];

export type GetApiPostsByIdTagsResponses = {
    /**
     * OK
     */
    200: Array<InternalApiTagItem>;
};

export type GetApiPostsByIdTagsResponse = GetApiPostsByIdTagsResponses[keyof GetApiPostsByIdTagsResponses];

export type GetApiScrapStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/scrap/status';
};

export type GetApiScrapStatusErrors = {
    /**
     * Unauthorized
     */
    401: InternalApiErrorResponse;
};

export type GetApiScrapStatusError = GetApiScrapStatusErrors[keyof GetApiScrapStatusErrors];

export type GetApiScrapStatusResponses = {
    /**
     * OK
     */
    200: InternalApiWorkerStatusResponse;
};

export type GetApiScrapStatusResponse = GetApiScrapStatusResponses[keyof GetApiScrapStatusResponses];

export type GetApiScrapTriggerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/scrap/trigger';
};

export type GetApiScrapTriggerErrors = {
    /**
     * Unauthorized
     */
    401: InternalApiErrorResponse;
    /**
     * Conflict
     */
    409: InternalApiErrorResponse;
};

export type GetApiScrapTriggerError = GetApiScrapTriggerErrors[keyof GetApiScrapTriggerErrors];

export type GetApiScrapTriggerResponses = {
    /**
     * OK
     */
    200: InternalApiActionResponse;
};

export type GetApiScrapTriggerResponse = GetApiScrapTriggerResponses[keyof GetApiScrapTriggerResponses];

export type GetImagesEncoderByHashData = {
    body?: never;
    path: {
        /**
         * Post image filename with extension (e.g. 92f7b4d1add652d381a0f3ded55b3f3d.jpg)
         */
        hash: string;
    };
    query?: never;
    url: '/images/encoder/{hash}';
};

export type GetImagesEncoderByHashErrors = {
    /**
     * Invalid hash parameter
     */
    400: InternalApiErrorResponse;
    /**
     * AVIF encoding not available or image not found
     */
    404: InternalApiErrorResponse;
    /**
     * Video files are not supported
     */
    415: InternalApiErrorResponse;
    /**
     * Encoding error
     */
    500: InternalApiErrorResponse;
};

export type GetImagesEncoderByHashError = GetImagesEncoderByHashErrors[keyof GetImagesEncoderByHashErrors];

export type GetImagesEncoderByHashResponses = {
    /**
     * AVIF encoded image
     */
    200: unknown;
};

export type GetImagesPreviewByHashData = {
    body?: never;
    path: {
        /**
         * Post image hash or identifier
         */
        hash: string;
    };
    query?: never;
    url: '/images/preview/{hash}';
};

export type GetImagesPreviewByHashErrors = {
    /**
     * Not Found
     */
    404: InternalApiErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalApiErrorResponse;
};

export type GetImagesPreviewByHashError = GetImagesPreviewByHashErrors[keyof GetImagesPreviewByHashErrors];

export type GetImagesPreviewByHashResponses = {
    /**
     * Optimized WebP image
     */
    200: unknown;
};
